blog/urls.py
from django.urls import path
from .views import BlogView, BlogDetailView

app_name = 'blog'

urlpatterns = [
    path('', BlogView, name="blog"),
    path('<slug>/<int:pk>/', BlogDetailView, name='blog-detail'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainstore.urls', namespace='retechecommerce')),
    path('api/', include('mainstore.api.urls', namespace='mpesa')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#used for custom error 404page
handler404='ecommerce.views.Handleerr404'

mainstore/urls.py
from django.urls import path, include
from .views import (
                    IndexView,
                    ContactView,
                    ItemDetailView,
                    CartView,
                    CheckOut,
                    CustomerReview,
                    Shop,
                    WishList,
                    Team,
                    Portfolio,
                    About,
                    CartView,
                    AddToCart,RemoveFromCart, RemoveItemFromMainCart,
                    AddToWish, RemoveItemFromWishList,
                    ItemQuickView,
                    AddCoupon, ItemCategoryView, ItemSearchResults,
                    LipaNaMpesaView, register_urls,confirmation,validation, call_back, getAccessToken
                    )

app_name="retechecommerce"

urlpatterns = [
    path('', IndexView, name='index'),
    path('contact/', ContactView, name='contact' ),
    path('products/<slug>/', ItemDetailView, name='item-detail'),
    path('products/category/<slug>', ItemCategoryView, name='category-list' ),
    path('quickview/<slug>/', ItemQuickView, name="item-quick-view"),
    path('add-to-cart/<slug>/', AddToCart, name='add-to-cart'),
    path('add-coupon/', AddCoupon, name="add-coupon"),
    path('remove-from-cart/<slug>/', RemoveFromCart, name='remove-from-cart'),
    path('add-to-wishlist/<slug>/', AddToWish, name='add-to-wishlist'),
    path('cart/', CartView, name="cart"),
    path('checkout/', CheckOut, name="checkout"),
    path('customerreview/', CustomerReview, name='customer-review'),
    path('shop/', Shop, name='shop'),
    path('wishlist/', WishList, name='wishlist'),
    path('team/', Team, name='team'),
    path('portfolio/', Portfolio, name='portfolio'),
    path('about/', About, name='about'),
    path('remove-from-main-cart/<slug>/', RemoveItemFromMainCart, name='remove-from-main-cart'),
    path('remove-from-wishlist/<slug>/', RemoveItemFromWishList, name='remove-from-wishlist'),
    path('product/search/', ItemSearchResults, name='search-results'),
    
    #mpesa urls#
    path('checkout/lipa-na-mpesa/', LipaNaMpesaView, name='lipa-na-mpesa'),
    path('c2b/register/', register_urls, name="register_mpesa_validation"),
    path('c2b/confirmation/', confirmation, name="confirmation"),
    path('c2b/validation/', validation, name="validation"),
    path('c2b/callback/', call_back, name="call_back"),
    path('get-token/', getAccessToken, name='accessToken')
   
]

ecommerce/views.py
from django.shortcuts import render


def Handleerr404(request, exception):
    return render(request, '404.html')

ecommerce/templates/payments/mpesa_checkout.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Lipa na Mpesa
{% endblock title %}
    

{% block body %}
    
        <!-- Start Bradcaump area -->
        <div class="ht__bradcaump__area" style="background: rgba(0, 0, 0, 0) url('{% static 'images/bg/2.jpg' %}') no-repeat scroll center center / cover ;">
            <div class="ht__bradcaump__wrap">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="bradcaump__inner text-center">
                                <h2 class="bradcaump-title">About Us</h2>
                                <nav class="bradcaump-inner">
                                  <a class="breadcrumb-item" href="{% url 'retechecommerce:index' %}">Home</a>
                                  <span class="brd-separetor">/</span>
                                  <span class="breadcrumb-item active">About Us</span>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Bradcaump area --> 
        <!-- Start Our Store Area -->
        <section class="htc__store__area ptb--120 bg__white">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="section__title section__title--2 text-center">
                            <h2 class="title__line">Welcome To Retech Store</h2>
                            <div class="row">
                              <div class="col-md-12">
                                <form action="{% url 'retechecommerce:lipa-na-mpesa' %}" class="mpesa-form" method="post">
                                  {% csrf_token %}
                                  <div class="form">
                                    <label for="mpesaNo">Enter Mpesa Number</label>
                                    <div class="form-group">
                                      <input class="form-control" type="text" name="phone-no" id="mpesaNo" placeholder="eg.712860997">
                                    </div>
  
                                    <button class="btn btn-primary" type="submit">Submit</button>
                                  </div>
                                </form>
                              </div>
                            </div>
                        </div>
                        <div class="store__btn">
                            <a href="{% url 'retechecommerce:contact' %}">contact us</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- End Our Store Area -->
        
        <!-- Start brand Area -->
        <div class="htc__brand__area bg__white ptb--120">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <ul class="brand__list">
                            <li><a href="#">
                                <img src="{% static 'images/brand/1.png' %}" alt="brand images">
                            </a></li>
                            <li><a href="#">
                                <img src="{% static 'images/brand/2.png' %}" alt="brand images">
                            </a></li>
                            <li><a href="#">
                                <img src="{% static 'images/brand/3.png' %}" alt="brand images">
                            </a></li>
                            <li><a href="#">
                                <img src="{% static 'images/brand/4.png' %}" alt="brand images">
                            </a></li>
                            <li class="hidden-sm"><a href="#">
                                <img src="{% static 'images/brand/5.png' %}" alt="brand images">
                            </a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- End brand Area -->
        <!-- Start Footer Area -->
       
{% endblock body %}
    